### ISSUE TITLE
Imap support

### ISSUE THREAD

**Issue by defactomail** [albsch/snappymail-docker#1]
I recently installed snappy email through the cloudron application on a Ubuntu 20.04 server. I'm pretty sure it's a docker image. I'm trying to enable imap so I can use Thunderbird. So far Thunderbird recognized the mail server address and the SSL ports, but it rejects the same login credentials I use on the webmail interface.

How can I enable imap/smtp support in Snappy Mail?

Thanks.

**Comment by albsch** [comment]
What exactly are you trying to do? Connect Thunderbird to SnappyMail?

SnappyMail is a web client that connects to an existing email server, just like Thunderbird is a desktop client that connects to an existing email server. SnappyMail supports `imap/smtp` in the sense that it can connect to email servers that provide the `imap/smtp` protocol.

**Comment by albsch** [comment]
If that doesn't answer your question, it's best to ask the developer of SnappyMail himself:

https://github.com/the-djmaze/snappymail

This repository is just my private docker image of SnappyMail until there is a properly maintained one in the developer's repository.

**Comment by defactomail** [comment]
Thanks. Wonderful. You gave me a lead.
